name: Test and Build
on:
  pull_request:
    branches:
      - main

jobs:
  #   linting:
  #     name: Linting
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Checkout
  #         uses: actions/checkout@v2

  #       - name: Use Node.js 14
  #         uses: actions/setup-node@v2
  #         with:
  #           node-version: 14
  #           cache: "npm"

  #       - name: Install dependencies
  #         run: npm ci

  #       - name: Lint
  #         run: npm run lint

  testing:
    name: Testing
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?schema=public
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "npm"

      - run: npm ci
      - run: |
          PGPASSWORD=postgres psql -h 0.0.0.0 -U postgres -tc "CREATE EXTENSION IF NOT EXISTS uuid-ossp"
      - run: npx prisma db push
      - run: npx prisma generate
      - run: npm run build
      - run: npm start & wait-on http://localhost:3000
      - run: npm run test

  # prettier:
  #   name: Prettier
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Use Node.js 14
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 14
  #         cache: "npm"

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run prettier
  #       run: npm run format

  # build:
  #   runs-on: ubuntu-latest
  #   needs: [linting, testing, prettier]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: Use Node.js 14
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 14
  #         cache: "npm"

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Build
  #       run: npm run build
